### ISSUE TITLE
Items are permanently deleted instead of dropping

### ISSUE THREAD

**Issue by floral-qua-floral** [jredfox/norespawnscreen#11]
Version: No Respawn Screen 1.2.3, Evil Notch Lib 1.2.3.06, Forge 1.12.2-14.23.5.2838

Issue: Items do not drop. NRS and ENL are the only mods loaded.

Steps to reproduce:
1. Launch the game using the latest NRS and the latest stable ENL release
2. Open a world and obtain some items
3. Run /kill or die in any other way
4. Return to the point of death and observe the lack of items

Log: Available [here](https://hastebin.com/ejuxoxifeg.sql). Summary: I enter a superflat world, spawn two stacks of stone, and execute /kill. I then run /testfor to confirm that none of the stone is simply clipped into the ground or otherwise displaced - it was not dropped at all.

ModPack/ModList: Only NRS and its dependency

Additional note: I have also tested this with the latest Evil Notch Lib beta release, however the issue still occurred. Furthermore, I have observed that Quark's "Totem of Holding" grave entity does not spawn on death when that mod is included, however I have not tested it in isolation. It is likely caused by the same issue. Enabling Slow Respawn fixes the problem entirely, but it is not desirable to have the default config setting permanently delete an inventory's worth of items.

**Comment by jredfox** [comment]
I am thinking of just doing a re-write of this.

**Comment by jredfox** [comment]
> Version: No Respawn Screen 1.2.3, Evil Notch Lib 1.2.3.06, Forge 1.12.2-14.23.5.2838
> 
> Issue: Items do not drop. NRS and ENL are the only mods loaded.
> 
> Steps to reproduce:
> 
> 1. Launch the game using the latest NRS and the latest stable ENL release
> 2. Open a world and obtain some items
> 3. Run /kill or die in any other way
> 4. Return to the point of death and observe the lack of items
> 
> Log: Available [here](https://hastebin.com/ejuxoxifeg.sql). Summary: I enter a superflat world, spawn two stacks of stone, and execute /kill. I then run /testfor to confirm that none of the stone is simply clipped into the ground or otherwise displaced - it was not dropped at all.
> 
> ModPack/ModList: Only NRS and its dependency
> 
> Additional note: I have also tested this with the latest Evil Notch Lib beta release, however the issue still occurred. Furthermore, I have observed that Quark's "Totem of Holding" grave entity does not spawn on death when that mod is included, however I have not tested it in isolation. It is likely caused by the same issue. Enabling Slow Respawn fixes the problem entirely, but it is not desirable to have the default config setting permanently delete an inventory's worth of items.

try the 2.0.0 re-write I do not have any issues with it
