### ISSUE TITLE
unable to respawn if previous world was already dead

### ISSUE THREAD

**Issue by jredfox** [jredfox/norespawnscreen#7]
unable to respawn if previous world was already dead

**Comment by darkphan** [comment]
Is this where a player logs in and is dead such as this message?

[NSR] re-spawned dead player on login:zendarva

**Comment by jredfox** [comment]
yes It should be fixed for the latest if it's not I will re-open it.

**Comment by darkphan** [comment]
Yeah we were getting that with the latest version.

**Comment by jredfox** [comment]
it means you logged into the world and you were already dead is this correct? 0.0 HP meaning you already dropped your loot so I don't fire everything again just the re-create player method.

**Comment by darkphan** [comment]
Had a player that was stuck like that, I have even tried to delete his playerdata files and killing him, he still constantly would log in like.

**Comment by jredfox** [comment]
does it happen just with my mods I literally check the hp

**Comment by darkphan** [comment]
I have not been able to test that. We have about 115 or so mods in the pack.

**Comment by jredfox** [comment]
if it's occurring every time there is an issue however if the player isn't saving data that the hp > 0.0 then that can't be my issue

**Comment by darkphan** [comment]
every time that user logs in they get that message

**Comment by jredfox** [comment]
try without any other with this mod. Unable to reproduce most likely another mod. Add a couple mods one at a time after my mod when your inventory wipes remember those new mods that you never unhighlighted from throwing them in the mods folder are then send me the names and versions of the mods.

make sure your using the latest

**Comment by jredfox** [comment]
because based on what I seen if you remove my mod the player should be dead on login always that can't be my mod's issue so try taking out nsr and see what happens. Maybe they are setting the player dead on login and then get's updated to alive the next tick I could remove the other or statement. 

Try this in your modpack to and see if it fixes your issues **need feedback if it does fix the issue**:
uploaded to curseforge is the latest now test that since you wouldn't test the mediafire. I don't want to upload via curseforge unless I know something has been fixed

**Comment by jredfox** [comment]
well did you try the newer version and see if that fixed it feedback is required before a new public release since I either need the modpack link or the mod list in order to reproduce the bug and if you can't do that for all I know you it could have nothing to do with my mod's bug / doesn't exist

**Comment by jredfox** [comment]
unable to reproduce the bug since you didn't respond nessary info to reproduce the bug feel free to open an issue with your modpack link next time or mod list but, preferably modpack since exact versions are all there ensuring the bug should occur

**Comment by darkphan** [comment]
I was unable to test the build. It seemed to only effect one player that has been helping test things. If I re-add the NSR mod and run across the issue again I will let you know all the info as to what mods we are using etc. Thanks.

**Comment by jredfox** [comment]
@darkphan test the latest version via curseforge and see if the player inventory wipes on login with your modpack look for the log as well.

if it occurs re-open as a new issue. Most likley not mine but, it would give me the ability to tell which mod is doing it so you can report an issue there because the player's health should always be above 0.0F that's the equalivent for isDead for the EntityPlayer since when the player dies isDead = false still I believe most of the time
